# Generated by Django 5.1.2 on 2024-11-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('idCuenta', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('codClase', models.IntegerField()),
                ('rubro', models.IntegerField()),
                ('codMayor', models.IntegerField()),
                ('codCuenta', models.TextField()),
                ('nameCuenta', models.TextField()),
                ('codDetalle', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'cuentas',
                'managed': False,
            },
        ),
    ]
