# Generated by Django 5.1.2 on 2024-11-05 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogocuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='saldosTransaccion',
            fields=[
                ('idSaldoTransaccion', models.AutoField(primary_key=True, serialize=False)),
                ('idTransaccion', models.IntegerField()),
                ('idCuenta', models.CharField(max_length=2)),
                ('debeTransaccion', models.IntegerField()),
                ('haberTransaccion', models.IntegerField()),
                ('fechaTransaccion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('idTransaccion', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('numPartida', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('idCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogocuentas.cuenta')),
                ('idSaldoTransaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtransacciones.saldostransaccion')),
            ],
            options={
                'db_table': 'gtransacciones_transaction',
                'ordering': ['fecha'],
            },
        ),
    ]
