# Generated by Django 5.1.2 on 2024-11-05 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtransacciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='idSaldoTransaccion',
        ),
        migrations.AlterField(
            model_name='saldostransaccion',
            name='debeTransaccion',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='saldostransaccion',
            name='haberTransaccion',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='saldostransaccion',
            name='idSaldoTransaccion',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='saldostransaccion',
            name='idTransaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtransacciones.transaction'),
        ),
    ]
