# Generated by Django 5.1.2 on 2024-11-13 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtransacciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saldostransaccion',
            name='fecha',
        ),
    ]
