# Generated by Django 5.1.2 on 2024-11-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtransacciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='saldosTransaccion',
            fields=[
                ('idSaldoTransaccion', models.AutoField(primary_key=True, serialize=False)),
                ('idTransaccion', models.IntegerField()),
                ('idCuenta', models.CharField(max_length=2)),
                ('debeTransaccion', models.IntegerField()),
                ('haberTransaccion', models.IntegerField()),
                ('fechaTransaccion', models.DateField()),
            ],
        ),
    ]
