# Generated by Django 5.1.2 on 2024-11-06 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtransacciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='idCuenta',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='numPartida',
        ),
    ]
