# Generated by Django 5.1.2 on 2024-11-14 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Junior', 'Junior'), ('Senior', 'Senior')], max_length=6)),
                ('salario_diario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dias_trabajo', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recargo_porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dias_vacaciones', models.IntegerField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costeo.empleado')),
            ],
        ),
    ]
