# Generated by Django 5.1.2 on 2024-11-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costeo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idProyecto', models.IntegerField()),
            ],
        ),
    ]
