# Generated by Django 5.1.2 on 2024-11-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costeo', '0002_cif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('imagen', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('meses_desarrollo', models.IntegerField()),
                ('horas_totales', models.IntegerField()),
                ('empleados', models.ManyToManyField(related_name='proyectos', to='costeo.empleado')),
            ],
        ),
    ]
