# Generated by Django 5.1.2 on 2024-11-15 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costeo', '0003_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cif',
            name='idProyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costeo.proyecto'),
        ),
    ]
