# Generated by Django 5.1.2 on 2024-11-05 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstadosFinancieros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='saldosEstados',
            fields=[
                ('idSaldoEstado', models.AutoField(primary_key=True, serialize=False)),
                ('idSaldo', models.CharField(max_length=2)),
                ('idEstado', models.ForeignKey(db_column='idEstado2', on_delete=django.db.models.deletion.CASCADE, to='EstadosFinancieros.estadosfinancieros')),
            ],
        ),
    ]
