# Generated by Django 5.1.2 on 2024-11-05 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstadosFinancieros', '0002_saldosestados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldosestados',
            name='idEstado',
            field=models.ForeignKey(db_column='idEstado', on_delete=django.db.models.deletion.CASCADE, to='EstadosFinancieros.estadosfinancieros'),
        ),
    ]
